{% set name = "smo" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smo-{{ version }}.tar.gz
  sha256: e6bd078874f7401d76c31d8ced0721b67cddae2658bba1ad22c0bf4baad94aed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - scipy
    - typing-extensions

test:
  imports:
    - smo
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/maurosilber/smo
  summary: Implementation of the Silver Mountain Operator (SMO) for the estimation of background distributions.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - maurosilber
