{% set name = "smo" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smo-{{ version }}.tar.gz
  sha256: 4d3f809a3e0ae08ec7fe720e0c246b1d2fea723ebfa8a2631fb67465be8d0b49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - scipy
    - typing-extensions

test:
  imports:
    - smo
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maurosilber/smo
  summary: Implementation of the Silver Mountain Operator (SMO) for the estimation of background distributions.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - maurosilber
